org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

group=at.yedel
modName=MeowConfig
modId=meowconfig
modDescription=Blazingly-fast, customizable and tracked meows
modIcon=assets/meowconfig/meowconfig.png
version=1.0.0
versionType=STABLE
license=LGPL-3.0-only
modrinthId=2KODyVqu
modrinthLogoLink=https://cdn.modrinth.com/data/cached_images/53192c4fe1fda4c27ff5e9caf380ab13262dbebe_0.webp