org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
loomx.loom_version=1.17.4

group=at.yedel
version=1.0.0
versionType=STABLE
mod.name=MeowConfig
mod.id=meowconfig
mod.description=Blazingly-fast, customizable and tracked meows
modIcon=assets/meowconfig/meowconfig.png
license=LGPL-3.0-only
modrinthId=2KODyVqu
modrinthLogoLink=https://cdn.modrinth.com/data/cached_images/53192c4fe1fda4c27ff5e9caf380ab13262dbebe_0.webp